title: Smart and Witty Blog Title
description: A blog where I post stuff
theme: minima
author: Jaeyoon Cho
permalink: /blog/:year/:month/:day/:title

github_username:  JYC11

future: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag